package com.accumulate.entity;

public class User extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.username
     *
     * @mbg.generated Fri Jan 13 15:56:18 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.password
     *
     * @mbg.generated Fri Jan 13 15:56:18 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.removed
     *
     * @mbg.generated Fri Jan 13 15:56:18 CST 2017
     */
    private Boolean removed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.display_name
     *
     * @mbg.generated Fri Jan 13 15:56:18 CST 2017
     */
    private String displayName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.username
     *
     * @return the value of acc_user.username
     *
     * @mbg.generated Fri Jan 13 15:56:18 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.username
     *
     * @param username the value for acc_user.username
     *
     * @mbg.generated Fri Jan 13 15:56:18 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.password
     *
     * @return the value of acc_user.password
     *
     * @mbg.generated Fri Jan 13 15:56:18 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.password
     *
     * @param password the value for acc_user.password
     *
     * @mbg.generated Fri Jan 13 15:56:18 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.removed
     *
     * @return the value of acc_user.removed
     *
     * @mbg.generated Fri Jan 13 15:56:18 CST 2017
     */
    public Boolean getRemoved() {
        return removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.removed
     *
     * @param removed the value for acc_user.removed
     *
     * @mbg.generated Fri Jan 13 15:56:18 CST 2017
     */
    public void setRemoved(Boolean removed) {
        this.removed = removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.display_name
     *
     * @return the value of acc_user.display_name
     *
     * @mbg.generated Fri Jan 13 15:56:18 CST 2017
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.display_name
     *
     * @param displayName the value for acc_user.display_name
     *
     * @mbg.generated Fri Jan 13 15:56:18 CST 2017
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }
}